spring.application.name=SHARE-server
spring.mongodb.uri=${MONGO.URI}
jwt.secret=${JWT.SECRET}
ai.key=${AI.KEY}
spring.cloud.gcp.project-id=share-server-490107
spring.cloud.gcp.credentials.json-key=${GCS.KEY}