spring.application.name=SHARE-server
spring.mongodb.uri=${MONGO.URI}
jwt.secret=${JWT.SECRET}
ai.key=${AI.KEY}
gmaps.key=${GMAPS.KEY}
spring.cloud.gcp.project-id=share-server-490107
spring.cloud.gcp.credentials.json-key=${GCS.KEY}
spring.autoconfigure.exclude=com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration,com.google.cloud.spring.autoconfigure.storage.GcpStorageAutoConfiguration
gcs.bucket.photo.name=photo-share-server
gcs.bucket.mob.photo.name=photo-mob
gcs.bucket.item.photo.name=photo-item
gcs.bucket.battle.photo.name=photo-battle
gcs.bucket.gmaps.photo.name=photo-gmaps
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

firebase.service.account.path=${FIREBASE_SERVICE_ACCOUNT_PATH:}
firebase.service.account.json=${FIREBASE_SERVICE_ACCOUNT_JSON:}

